# Usage: cmake -DKERNEL_FILES="a.cl;b.cl" -DOUT_FILE=... -P EmbedKernels.cmake
# Emits one  inline const char* k<CamelBasename>ClSource = R"CLSRC(...)CLSRC";
# per input file into a single header under namespace mxbm::gpu.
file(WRITE "${OUT_FILE}" "#pragma once\n// GENERATED by EmbedKernels.cmake — do not edit.\nnamespace mxbm { namespace gpu {\n")
foreach(f ${KERNEL_FILES})
  get_filename_component(base "${f}" NAME_WE)          # e.g. bh3
  string(SUBSTRING "${base}" 0 1 first)
  string(SUBSTRING "${base}" 1 -1 rest)
  string(TOUPPER "${first}" first)
  set(sym "k${first}${rest}ClSource")                  # kBh3ClSource
  file(READ "${f}" body)
  if(body MATCHES [[\)CLSRC"]])
    message(FATAL_ERROR "CLSRC delimiter collision in ${f}")
  endif()
  file(APPEND "${OUT_FILE}" "inline const char* ${sym} = R\"CLSRC(\n${body}\n)CLSRC\";\n")
endforeach()
file(APPEND "${OUT_FILE}" "} }\n")
