# Usage: cmake -DKERNEL_FILES="a.cl;b.cl" -DOUT_FILE=... -P EmbedKernels.cmake
# Emits one NUL-terminated byte array + `inline const char* k<Base>ClSource`
# per input file, under namespace mxbm::gpu. Bytes, not a string literal:
# MSVC caps a literal at 16380 bytes (65535 concatenated) and lds.cl is 82 KB.
file(WRITE "${OUT_FILE}" "#pragma once\n// GENERATED by EmbedKernels.cmake — do not edit.\nnamespace mxbm { namespace gpu {\n")
foreach(f ${KERNEL_FILES})
  get_filename_component(base "${f}" NAME_WE)          # e.g. bh3
  string(SUBSTRING "${base}" 0 1 first)
  string(SUBSTRING "${base}" 1 -1 rest)
  string(TOUPPER "${first}" first)
  set(sym "k${first}${rest}ClSource")                  # kBh3ClSource
  file(READ "${f}" hex HEX)
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," hex "${hex}")
  # Wrap every 24 bytes; a multi-hundred-KB logical line is its own compiler risk.
  string(REPEAT "0x[0-9a-f][0-9a-f]," 24 pair24)
  string(REGEX REPLACE "(${pair24})" "\\1\n" hex "${hex}")
  # unsigned char: kernel comments contain UTF-8 bytes >= 0x80, which do not
  # list-initialize a (signed) char without a narrowing error.
  file(APPEND "${OUT_FILE}" "inline const unsigned char ${sym}_bytes[] = {\n${hex}0x00};\ninline const char* ${sym} = reinterpret_cast<const char*>(${sym}_bytes);\n")
endforeach()
file(APPEND "${OUT_FILE}" "} }\n")
